import type { Metadata, Viewport } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

export const metadata: Metadata = {
  title: "Ariel Silva",
  description: "Generated by create next app",
};

// <meta name="viewport" content="width=device-width, initial-scale=1.0" />
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen h-screen bg-black antialiased">
        {children}
      </body>
    </html>
  );
}
